framework:
    messenger:
        # Uncomment this (and the failed transport below) to send failed messages to this transport for later handling.
        failure_transport: failed

        transports:
            # https://symfony.com/doc/current/messenger.html#transport-configuration
            async:
                dsn: '%env(MESSENGER_TRANSPORT_DSN)%'
                options:
                    table_name: messenger_messages
                    queue_name: default
                    redeliver_timeout: 3600
                    auto_setup: true

            failed:
                dsn: '%env(MESSENGER_TRANSPORT_DSN)%'
                options:
                    table_name: messenger_failed_messages
                    queue_name: failed
                    redeliver_timeout: 3600
                    auto_setup: true
            # sync: 'sync://'

        routing:
            # Route your messages to the transports
            'Customize\Message\AutionNotification': async
